---
collections:
  - source: ./sfey/hierarch
    type: dir
  - name: community.postgresql
  - name: community.crypto
  - name: geerlingguy.certbot
  - name: nginxinc.nginx
  - name: nginxinc.nginx_config
