---
- name: Unlock ssh key
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Unlock SSH key "{{ ssh_key_file | expandvars }}"
      ansible.builtin.expect:
        command: ssh-add "{{ ssh_key_file | expandvars }}"
        responses:
          passphrase: "{{ ssh_key_pass }}"
      become: false
      changed_when: false
      no_log: true
- name: Configure admin server
  hosts: admin
  tasks:
    - name: Give postgres role
      ansible.builtin.import_role:
        name: sfey.hierarch.postgres
      become: true
    - name: Give letsencryptnginx role
      ansible.builtin.import_role:
        name: sfey.hierarch.letsencryptnginx
      become: true
    - name: Give keycloak role
      ansible.builtin.import_role:
        name: sfey.hierarch.keycloak
      become: true
- name: Clean up
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Lock SSH key "{{ ssh_key_file | expandvars }}"
      ansible.builtin.command: ssh-add -d "{{ ssh_key_file | expandvars }}"
      become: false
      changed_when: false
      register: result
      failed_when: result.rc != 0
