---
- name: Unlock ssh key
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Unlock SSH key "{{ ssh_key_file | expandvars }}"
      ansible.builtin.expect:
        command: ssh-add "{{ ssh_key_file | expandvars }}"
        responses:
          passphrase: "{{ ssh_key_pass }}"
      become: false
      changed_when: false
      no_log: true
- name: Configure admin server
  hosts: admin
  tasks:
    - name: Include admin_setup.yml tasks
      ansible.builtin.import_tasks: tasks/admin_setup.yml
- name: Configure mail server
  hosts: mail
  tasks:
    - name: Give mailcow role
      ansible.builtin.import_role:
        name: sfey.hierarch.mailcow
      become: true
- name: Setup keycloak realm and roles
  hosts: admin
  tasks:
    - name: Include kc_realm.yml tasks
      ansible.builtin.import_tasks: tasks/kc_realm.yml
- name:
  hosts: app
  tasks:
    - name: Include app_setup.yml tasks
      ansible.builtin.import_tasks: tasks/app_setup.yml
- name: Clean up
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Lock SSH key "{{ ssh_key_file | expandvars }}"
      ansible.builtin.command: ssh-add -d "{{ ssh_key_file | expandvars }}"
      become: false
      changed_when: false
      register: result
      failed_when: result.rc != 0
