---
- hosts: localhost
  name: Generate certificates
  gather_facts: false
  tasks:
    - name: Generate postgres SSL privkey
      community.crypto.openssl_privatekey:
        path: "{{ kc_local_key_file }}"
        type: Ed25519
      become: false
    - name: Generate postgres SSL certificate
      community.crypto.x509_certificate:
        path: "{{ kc_local_cert_file }}"
        privatekey_path: "{{ kc_local_key_file }}"
        provider: selfsigned
      become: false
    - name: Unlock SSH key "{{ ssh_key_file | expandvars }}"
      ansible.builtin.expect:
        command: ssh-add "{{ ssh_key_file | expandvars }}"
        responses:
          passphrase: "{{ ssh_key_pass }}"
      become: false
      changed_when: false
      no_log: true
- hosts: admin
  name: Configure admin server
  tasks:
    - name: Give postgres role
      ansible.builtin.import_role:
        name: sfey.hierarch.postgres
      become: true
- hosts: localhost
  name: Clean up
  gather_facts: false
  tasks:
    - name: Lock SSH key "{{ ssh_key_file | expandvars }}"
      ansible.builtin.command: ssh-add -d "{{ ssh_key_file | expandvars }}"
      become: false
      changed_when: false
      register: result
      failed_when: result.rc != 0
