# put these in vault.yml
# fj_user:
# fj_pass:
# fj_secret_key:
# fj_internal_key:
ufw_allowed_in:
  tcp:
    - "80"
    - "443"
    - "1001"
    - "3478,3479,5349,5350"
  udp:
    - "3478,3479,5349,5350"
    - "49152:65535"
ufw_limit_in:
  tcp:
    - "22"
  udp: []
fj_download_link: "https://codeberg.org/forgejo/forgejo/releases/download/v1.21.6-0/forgejo-1.21.6-0-linux-amd64"
fj_email: contact@hierarch.live
fj_version: "1.21.6-0-amd64"
fj_image: "codeberg.org/forgejo/forgejo"
fj_mailer_from: "noreply@hierarch.live"
fj_host: "git.hierarch.live"
fj_ssh_port: "1001"
fj_http_port: "7001"
smtp_port: "587"
smtp_host: "smtp.mailgun.org"
smtp_type: "smtp+starttls"
domain_name: app.hierarch.live
oidc_url: "https://admin.hierarch.live/realms/hierarch/.well-known/openid-configuration"
oidc_realm_url: "https://admin.hierarch.live/realms/hierarch"
oidc_id: forgejo
db_hostname: localhost
db_is_local: true
mx_host: "chat.hierarch.live"
wk_db_name: wikijs
wk_db_user: hrwikijs
db_databases:
  - name: forgejo
    user: "{{ fj_db_user }}"
    pass: "{{ fj_db_pass }}"
    schema: forgejo
    origin: "127.0.0.1"
    ipv6_origin: ""
    collate: ""
    public_schema: false
  - name: "{{ mx_db_name }}"
    user: "{{ mx_db_user }}"
    pass: "{{ mx_db_pass }}"
    schema: "{{ mx_db_name }}"
    origin: "127.0.0.1"
    ipv6_origin: ""
    collate: C
    public_schema: true
  - name: "{{ wk_db_name }}"
    user: "{{ wk_db_user }}"
    pass: "{{ wk_db_pass }}"
    schema: "{{ wk_db_name }}"
    origin: "127.0.0.1"
    ipv6_origin: ""
    collate: ""
    public_schema: false
server_names:
  - "{{ fj_host }}"
admin_email: fey.sasha@gmail.com
certs:
  - domains:
      - "{{ domain_name }}"
      - "www.{{ domain_name }}"
      - "{{ fj_host }}"
      - "www.{{ fj_host }}"
      - "{{ mx_host }}"
      - "www.{{ mx_host }}"
      - "{{ wk_host }}"
      - "www.{{ wk_host }}"
      - "{{ hr_host }}"
      - "www.{{ hr_host }}"
      - "{{ doc_host }}"
      - "www.{{ doc_host }}"
      - "{{ sandbox_host }}"
      - "www.{{ sandbox_host }}"
stop_services:
  - nginx
upstreams_forgejo:
  - name: forgejo
    servers:
      - address: localhost:7001
upstreams_synapse:
  - name: synapse
    servers:
      - address: localhost:7002
upstreams_wiki:
  - name: wikijs
    servers:
      - address: localhost:7003
upstreams_doc:
  - name: cryptpad
    servers:
      - address: localhost:7004
  - name: cryptsandbox
    servers:
      - address: localhost:7005
  - name: cryptwebsocket
    servers:
      - address: localhost:7006
nginx_fj_locations:
  - location: /
    proxy:
      pass: http://forgejo
      http_version: 1.1
nginx_mx_locations:
  - location: '~ ^(/_matrix|/_synapse/client)'
    proxy:
      pass: http://synapse
      http_version: 1.1
  - location: /
    core:
      root: /usr/share/element-web
  - location: "= /.well-known/matrix/server"
    proxy:
      pass: http://synapse
      http_version: 1.1
  - location: "= /.well-known/matrix/client"
    rewrite:
      return:
        code: 200
        text: "'{\"m.homeserver\": {\"base_url\": \"https://{{ mx_host }}\"}}'"
    core:
      default_type: application/json
    headers:
      add_headers:
        - name: Access-Control-Allow-Origin
          value: '*'
          always: true
nginx_wk_locations:
  - location: /
    proxy:
      pass: http://wikijs
      http_version: 1.1
nginx_doc_locations:
  - location: /
    proxy:
      pass: http://cryptpad
      set_header:
        - field: Upgrade
          value: $http_upgrade
        - field: Connection
          value: upgrade
      http_version: 1.1
  - location: '^~ /cryptpad_websocket'
    proxy:
      pass: http://cryptwebsocket
      set_header:
        - field: Upgrade
          value: $http_upgrade
        - field: Connection
          value: upgrade
postgres_remote_cert_file: "/etc/letsencrypt/live/{{ domain_name }}-0003/cert.pem"
postgres_remote_key_file: "/etc/letsencrypt/live/{{ domain_name }}-0003/privkey.pem"
postgres_local_cert_file: /etc/postgresql/15/main/cert.pem
postgres_local_key_file: /etc/postgresql/15/main/privkey.pem
cert_file: "/etc/letsencrypt/live/{{ domain_name }}-0003/fullchain.pem"
cert_key: "/etc/letsencrypt/live/{{ domain_name }}-0003/privkey.pem"
servers_forgejo:
  - core:
      listen:
        - address: "0.0.0.0"
          port: 443
          default_server: false
          ssl: true
          http2: true
        - address: "[::]"
          port: 443
          default_server: false
          ssl: true
          http2: true
      server_name: "{{ fj_host }}"
    locations: "{{ nginx_fj_locations }}"
servers_synapse:
  - core:
      listen:
        - address: "0.0.0.0"
          port: 443
          default_server: false
          ssl: true
          http2: true
        - address: "[::]"
          port: 443
          default_server: false
          ssl: true
          http2: true
      server_name: "{{ mx_host }}"
    locations: "{{ nginx_mx_locations }}"
servers_wiki:
  - core:
      listen:
        - address: "0.0.0.0"
          port: 443
          default_server: false
          ssl: true
          http2: true
        - address: "[::]"
          port: 443
          default_server: false
          ssl: true
          http2: true
      server_name: "{{ wk_host }}"
    locations: "{{ nginx_wk_locations }}"
servers_doc:
  - core:
      listen:
        - address: "0.0.0.0"
          port: 443
          default_server: false
          ssl: true
          http2: true
        - address: "[::]"
          port: 443
          default_server: false
          ssl: true
          http2: true
      server_name: "{{ doc_host }} {{ sandbox_host }}"
    locations: "{{ nginx_doc_locations }}"
    # headers:
    #   add_headers:
    #     - name: Strict-Transport-Security
    #       value: "\"max-age=63072000; includeSubDomains\""
    #       always: true
http_templates:
  - backup: true
    deployment_location: /etc/nginx/conf.d/default.conf
    config:
      core:
        client_max_body_size: 50m
      ssl:
        certificate: "{{ cert_file }}"
        certificate_key: "{{ cert_key }}"
        ciphers:
          - HIGH
          - "!aNull"
          - "!MD5"
        conf_command: Protocol TLSv1.2
        prefer_server_ciphers: false
        protocols:
          - TLSv1.2
          - TLSv1.3
      proxy:
        set_header:
          - field: X-Forwarded-For
            value: $proxy_add_x_forwarded_for
          - field: X-Forwarded-Proto
            value: $scheme
          - field: X-Fowarded-Host
            value: $host
          - field: Host
            value: $http_host
          - field: User-Agent
            value: $http_user_agent
          - field: X-Real-IP
            value: $remote_addr
        buffering: false
      log:
        access:
          - path: /var/log/nginx/access.log
            format: main
            buffer: 1m
            gzip: 5
            flush: 10h
            if: $status
        format:
          - name: main
            format: |
              '$remote_addr - $remote_user [$time_local] "$request" '
              '$status $body_bytes_sent "$http_referer" '
              '"$http_user_agent" "$http_x_forwarded_for"'
        error_log:
          file: /var/log/nginx/error.log
          level: notice
        open_log_file_cache:
          max: 1000
          inactive: 20s
          min_uses: 2
          valid: 1m
      servers:
        - core:
            listen:
              - address: "0.0.0.0"
                port: 80
                default_server: true
                ssl: false
              - address: "[::]"
                port: 80
                default_server: true
                ssl: false
          rewrite:
            return:
              code: 301
              url: "https://$host$request_uri"
  - backup: true
    deployment_location: /etc/nginx/conf.d/forgejo.conf
    config:
      upstreams: "{{ upstreams_forgejo }}"
      servers: "{{ servers_forgejo }}"
  - backup: true
    deployment_location: /etc/nginx/conf.d/synapse.conf
    config:
      upstreams: "{{ upstreams_synapse }}"
      servers: "{{ servers_synapse }}"
  - backup: true
    deployment_location: /etc/nginx/conf.d/wiki.conf
    config:
      upstreams: "{{ upstreams_wiki }}"
      servers: "{{ servers_wiki }}"
  - backup: true
    deployment_location: /etc/nginx/conf.d/cryptpad.conf
    config:
      upstreams: "{{ upstreams_doc }}"
      servers: "{{ servers_doc }}"
      ssl:
        dhparam: /etc/dhparam.pem
        session_cache:
          builtin:
            enable: true
            size: 20480
        session_tickets: false
        session_timeout: 1d
nginx_confs:
  - /etc/nginx/conf.d/default.conf
  - /etc/nginx/conf.d/forgejo.conf
  - /etc/nginx/conf.d/synapse.conf
  - /etc/nginx/conf.d/wiki.conf
  - /etc/nginx/conf.d/cryptpad.conf
mx_config_dir: "/etc/matrix-synapse/conf.d"
mx_user: hr-synapse
mx_db_user: hrsynapse
mx_db_name: synapse
turn_allowed_peer_ip: "104.219.236.22"
wk_host: "wiki.hierarch.live"
wk_home_dir: "/srv/wikijs"
wk_base_dir: "{{ wk_home_dir }}/wiki"
kc_name: keycloak
hr_host: "hr.hierarch.live"
doc_host: "docs.hierarch.live"
doc_base_url: "https://{{ doc_host }}"
sandbox_host: "sandbox.hierarch.live"
sandbox_base_url: "https://{{ sandbox_host }}"
doc_home_dir: "/opt/cryptpad"
doc_base_dir: "{{ doc_home_dir }}/doc"
doc_version: "5.7.0"
doc_repo: "https://github.com/cryptpad/cryptpad.git"
doc_sso_repo: "https://github.com/cryptpad/sso"
doc_admin_keys: "[\"[hr-cryptpad@docs.hierarch.live/Wv-xZAQ3H8+0VNaAifjgiDbiK9JyZj-H4UlXJ4Q1Gjw=]\"]"
runner_download: "https://code.forgejo.org/forgejo/runner/releases/download/v3.0.0/forgejo-runner-3.0.0-linux-amd64"
runner_verify_download: "https://code.forgejo.org/forgejo/runner/releases/download/v3.0.0/forgejo-runner-3.0.0-linux-amd64.asc"
runner_verify_fingerprint: "EB114F5E6C0DC2BCDD183550A4B61A2DC5923710"
runner_dir: /opt/runner
