# put these in vault.yml
# fj_user:
# fj_pass:
# fj_secret_key:
# fj_internal_key:
fj_email: contact@hierarch.live
fj_version: "1.21.6-0-arm64-rootless"
fj_image: "codeberg.org/forgejo/forgejo"
fj_mailer_from: "noreply@hierarch.live"
fj_host: "git.hierarch.live"
fj_env: "{{ fj_env_default }}"
fj_ssh_port: "1001"
fj_http_port: "7001"
smtp_port: "587"
smtp_host: "smtp.mailgun.org"
smtp_type: "smtp+starttls"
fj_env_default: |
  USER_UID=1000
  USER_GID=1000
  LFS_START_SERVER=true
  FORGEJO__security__INSTALL_LOCK=true
  FORGEJO__server__DOMAIN={{ fj_host }}
  FORGEJO__server__SSH_DOMAIN={{ fj_host }}
  FORGEJO__server__ROOT_URL=https://{{ fj_host }}/
  FORGEJO__server__ENABLE_ACME=false
  FORGEJO__server__HTTP_PORT={{ fj_http_port }}
  FORGEJO__server__SSH_PORT={{ fj_ssh_port }}
  FORGEJO__repository__ENABLE_PUSH_CREATE_USER=true
  FORGEJO__repository__ENABLE_PUSH_CREATE_ORG=true
  FORGEJO__repository__DEFAULT_REPO_UNITS=repo.code,repo.releases,repo.issues,repo.pulls,repo.wiki,repo.projects,repo.packages,repo.actions
  FORGEJO__actions__ENABLED=true
  FORGEJO__service__DEFAULT_KEEP_EMAIL_PRIVATE=false
  FORGEJO__service__DEFAULT_USER_VISIBILITY=limited
  FORGEJO__service__ALLOWED_USER_VISIBILITY_MODES=limited
  FORGEJO__service__DEFAULT_ORG_VISIBILITY=limited
  FORGEJO__service__REQUIRE_SIGNIN_VIEW=true
  FORGEJO__service__ENABLE_NOTIFY_MAIL=true
  FORGEJO__service__ALLOW_ONLY_EXTERNAL_REGISTRATION=true
  FORGEJO__service__DISABLE_REGISTRATION=false
  FORGEJO__ui__DEFAULT_THEME=gitea-dark
  FORGEJO__admin__DISABLE_REGULAR_ORG_CREATION=true
  FORGEJO__security__COOKIE_USERNAME=hrgituser
  FORGEJO__security__COOKIE_REMEMBER_NAME=hrgitrem
  FORGEJO__mailer__ENABLED=true
  FORGEJO__mailer__FROM={{ fj_mailer_from }}
  FORGEJO__mailer__PROTOCOL={{ smtp_type }}
  FORGEJO__mailer__SMTP_PORT={{ smtp_port }}
  FORGEJO__mailer__SMTP_ADDR={{ smtp_host }}
  FORGEJO__session__PROVIDER=postgres
  FORGEJO__session__COOKIE_NAME=hrgitsess
  FORGEJO__session__COOKIE_SECURE=true
  FORGEJO__session__SAME_SITE=strict
  FORGEJO__APP_NAME=Hierarch Forgejo
  FORGEJO__openid__ENABLE_OPENID_SIGNIN=true
  FORGEJO__openid__ENABLE_OPENID_SIGNUP=true
  FORGEJO__openid__WHITELISTED_URIS={{ db_hostname }}
  FORGEJO__oauth2_client__REGISTER_EMAIL_CONFIRM=false
  FORGEJO__oauth2_client__OPENID_CONNECT_SCOPES=openid profile email
  FORGEJO__oauth2_client__ENABLE_AUTO_REGISTRATION=true
  FORGEJO__oauth2_client__UPDATE_AVATAR=true
  FORGEJO__oauth2__ENABLED=false
  FORGEJO__database__DB_TYPE: postgres
  FORGEJO__database__HOST={{ db_hostname }}:5432
  FORGEJO__database__NAME=forgejo
  FORGEJO__database__USER={{ jf_db_user }}
  FORGEJO__database__PASSWD={{ fj_db_pass }}
  FORGEJO__database__SCHEMA=forgejo
  FORGEJO__database__SSL_MODE=require
  FORGEJO__security__SECRET_KEY={{ fj_secret_key }}
  FORGEJO__security__INTERNAL_TOKEN={{ fj_internal_key }}
  FORGEJO__mailer__USER={{ fj_smtp_user }}
  FORGEJO__mailer__PASSWD={{ fj_smtp_pass }}
  --
domain_name: app.hierarch.live
server_names:
  - "{{ fj_host }}"
admin_email: fey.sasha@gmail.com
certs:
  - domains:
      - "{{ domain_name }}"
      - "www.{{ domain_name }}"
      - "{{ fj_host }}"
      - "www.{{ fj_host }}"
stop_services:
  - nginx
nginx_upstreams:
  - name: forgejo
    servers:
      - address: localhost:7001
nginx_fj_locations:
  - location: /
    proxy:
      pass: http://forgejo
cert_file: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
cert_key: "/etc/letsencrypt/live/{{ domain_name }}/privkey.pem"
servers:
  - core:
      listen:
        - address: "0.0.0.0"
          port: 80
          default_server: true
          ssl: false
        - address: "[::]"
          port: 80
          default_server: true
          ssl: false
    rewrite:
      return:
        code: 301
        url: "https://$host$request_uri"
  - core:
      listen:
        - address: "0.0.0.0"
          port: 443
          default_server: false
          ssl: true
          reuseport: true
          so_keepalive: true
        - address: "[::]"
          port: 443
          default_server: false
          ssl: true
          reuseport: true
          so_keepalive: true
      server_name: "{{ fj_host }}"
    locations: "{{ nginx_fj_locations }}"
