---
# put these in vault.yml
# fj_pass:
# fj_secret_key:
# fj_internal_key:
# fj_user:
# fj_smtp_user:
# fj_smtp_pass:
# mx_pass:
# mx_db_pass:
# mx_smtp_user:
# mx_smtp_pass:
# mx_shared_secret:
# turn_auth_secret:
# turn_cli_pass:
# wk_db_pass:
# doc_login_salt:
# runner_secret:
# hr_admin_pass:
# hr_db_pass:
# hr_db_root_pass:
# fj_lfs_secret:
fj_download_link: "https://codeberg.org/forgejo/forgejo/releases/download/v1.21.6-0/forgejo-1.21.6-0-linux-amd64"
fj_email: contact@hierarch.live
fj_image: "codeberg.org/forgejo/forgejo"
fj_mailer_from: "noreply@hierarch.live"
smtp_port: "587"
smtp_host: "smtp.mailgun.org"
smtp_type: "smtp+starttls"
domain_name: app.hierarch.live
mx_user: hr-synapse
turn_allowed_peer_ip: "104.219.236.22"
kc_name: keycloak
runner_download: "https://code.forgejo.org/forgejo/runner/releases/download/v3.0.0/forgejo-runner-3.0.0-linux-amd64"
runner_verify_download: "https://code.forgejo.org/forgejo/runner/releases/download/v3.0.0/forgejo-runner-3.0.0-linux-amd64.asc"
runner_verify_fingerprint: "EB114F5E6C0DC2BCDD183550A4B61A2DC5923710"
wk_db_name: wikijs
wk_db_user: hrwikijs
mx_db_user: hrsynapse
mx_db_name: synapse
