all:
  vars:
    ansible_user: sfey
ungrouped:
  hosts:
    localhost:
      ansible_python_interpreter: "~/.local/pipx/venvs/ansible/bin/python3"
      ansible_connection: local
admin:
  hosts:
    admin01:
      ansible_host: 77.90.8.143
mail:
  hosts:
    mail01:
      ansible_host: 77.90.8.144
app:
  hosts:
    app01:
      ansible_host: 104.219.236.22
      ipv6: "2605:aa80:3:a5ed::1"
dev:
  children:
    admin:
    app:
    mail:
