all:
  vars:
    ansible_user: sfey
ungrouped:
  hosts:
    localhost:
      ansible_python_interpreter: "~/.local/pipx/venvs/ansible/bin/python3"
      ansible_connection: local
admin:
  hosts:
    admin01:
      ansible_host: 192.168.88.135
dev:
  children:
    admin:
