---
- name: Give ufw role
  ansible.builtin.import_role:
    name: sfey.hierarch.ufw
  become: true
- name: Give letsencryptnginx role
  ansible.builtin.import_role:
    name: sfey.hierarch.letsencryptnginx
  become: true
- name: Give postgres role
  ansible.builtin.import_role:
    name: sfey.hierarch.postgres
  become: true
- name: Give keycloak role
  ansible.builtin.import_role:
    name: sfey.hierarch.keycloak
  become: true
