---
# - name: Give letsencryptnginx role
#   ansible.builtin.import_role:
#     name: sfey.hierarch.letsencryptnginx
#   become: true
#     - name: Install docker-ce role
#       ansible.builtin.import_role:
#         name: haxorof.docker_ce
- name: Give forgejo role
  ansible.builtin.import_role:
    name: sfey.hierarch.forgejo
  become: true
