---
#     - name: Install docker-ce role
#       ansible.builtin.import_role:
#         name: haxorof.docker_ce
- name: Give letsencryptnginx role
  ansible.builtin.import_role:
    name: sfey.hierarch.letsencryptnginx
  become: true
- name: Give postgres role
  ansible.builtin.import_role:
    name: sfey.hierarch.postgres
  become: true
- name: Give forgejo role
  ansible.builtin.import_role:
    name: sfey.hierarch.forgejo
  become: true
- name: Give synapse role
  ansible.builtin.import_role:
    name: sfey.hierarch.synapse
  become: true
- name: Give wikijs role
  ansible.builtin.import_role:
    name: sfey.hierarch.wikijs
  become: true
