---
# - name: Give ufw role
#   ansible.builtin.import_role:
#     name: sfey.hierarch.ufw
#   become: true
# - name: Install docker-ce role
#   ansible.builtin.import_role:
#     name: haxorof.docker_ce
# - name: Give letsencryptnginx role
#   ansible.builtin.import_role:
#     name: sfey.hierarch.letsencryptnginx
#   become: true
- name: Give postgres role
  ansible.builtin.import_role:
    name: sfey.hierarch.postgres
  become: true
# - name: Give forgejo role
#   ansible.builtin.import_role:
#     name: sfey.hierarch.forgejo
#   become: true
# - name: Give runner role
#   ansible.builtin.import_role:
#     name: sfey.hierarch.runner
#   become: true
# - name: Give synapse role
#   ansible.builtin.import_role:
#     name: sfey.hierarch.synapse
#   become: true
# - name: Give wikijs role
#   ansible.builtin.import_role:
#     name: sfey.hierarch.wikijs
#   become: true
# - name: Give cryptpad role
#   ansible.builtin.import_role:
#     name: sfey.hierarch.cryptpad
#   become: true
# - name: Give orangehrm role
#   ansible.builtin.import_role:
#     name: sfey.hierarch.orangehrm
#   become: true
# - name: Configure backup target user
#   become: true
#   block:
#     - name: Create borg target user
#       ansible.builtin.user:
#         name: "{{ borg_backup_user }}"
#         state: present
#         password: "{{ borg_user_pass }}"
#         create_home: false
#         home: "{{ borg_home_dir }}"
#     - name: Create borg target home dir
#       ansible.builtin.file:
#         state: directory
#         path: "{{ borg_home_dir }}"
#         owner: "{{ borg_backup_user }}"
#         group: "{{ borg_backup_user }}"
#         mode: '770'
#     - name: Create borg .ssh dir
#       ansible.builtin.file:
#         state: directory
#         path: "{{ borg_home_dir }}/.ssh"
#         owner: "{{ borg_backup_user }}"
#         group: "{{ borg_backup_user }}"
#         mode: '700'
#     - name: Create authorized keys file
#       ansible.builtin.copy:
#         src: "resource/borg_ssh.pub"
#         dest: "{{ borg_home_dir }}/.ssh/authorized_keys"
#         owner: "{{ borg_backup_user }}"
#         group: "{{ borg_backup_user }}"
#         mode: '600'
- name: Give borgmatic role
  ansible.builtin.import_role:
    name: sfey.hierarch.borgmatic
  become: true
