---
borg_before_backup:
  - echo "Starting a backup"
borg_after_backup:
  - echo "Finished a backup."
borg_source_dirs:
  - /etc/nginx
  - /etc/letsencrypt
  - /etc/keycloak
  - /opt/keycloak
  - /opt/homepage
  - /etc/postgresql
  - /etc/systemd/system
borg_repos:
  - ssh://{{ borg_backup_user }}@{{ borg_backup_host }}{{ borg_home_dir }}/admin.borg
pg_backup_databases: true
