---
admin_email: fey.sasha@gmail.com
certs:
  - domains:
      - "{{ domain_name }}"
      - "{{ root_domain }}"
stop_services:
  - nginx
cert_file: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
cert_key: "/etc/letsencrypt/live/{{ domain_name }}/privkey.pem"
