---
nginx_upstreams:
  - name: keycloak
    servers:
      - address: 127.0.0.1:7000
  - name: homepage
    servers:
      - address: 127.0.0.1:3000
nginx_main_locations:
  - location: /admin # restrict
    proxy:
      pass: http://keycloak
  - location: /js # restrict
    proxy:
      pass: http://keycloak
  - location: /realms
    proxy:
      pass: http://keycloak
  - location: /resources
    proxy:
      pass: http://keycloak
  - location: /robots.txt
    proxy:
      pass: http://keycloak
nginx_hp_locations:
  - location: /
    proxy:
      pass: http://homepage
servers:
  - core:
      listen:
        - address: "0.0.0.0"
          port: 80
          default_server: true
          ssl: false
        - address: "[::]"
          port: 80
          default_server: true
          ssl: false
    rewrite:
      return:
        code: 301
        url: "https://$host$request_uri"
  - core:
      listen:
        - address: "0.0.0.0"
          port: 443
          default_server: false
          ssl: true
        - address: "[::]"
          port: 443
          default_server: false
          ssl: true
      server_name: "{{ domain_name }}"
    locations: "{{ nginx_main_locations }}"
    proxy:
      buffer_size: 256k
      buffers:
        number: 8
        size: 512k
      busy_buffers_size: 512k
  - core:
      listen:
        - address: "0.0.0.0"
          port: 443
          default_server: true
          ssl: true
        - address: "[::]"
          port: 443
          default_server: true
          ssl: true
      server_name: "hierarch.live"
    locations: "{{ nginx_hp_locations }}"
mx_base_url: "https://chat.hierarch.live"
http_templates:
  - backup: true
    config:
      upstreams: "{{ nginx_upstreams }}"
      ssl:
        certificate: "{{ cert_file }}"
        certificate_key: "{{ cert_key }}"
        ciphers:
          - HIGH
          - "!aNull"
          - "!MD5"
        conf_command: Protocol TLSv1.2
        prefer_server_ciphers: false
        protocols:
          - TLSv1.2
          - TLSv1.3
      proxy:
        set_header:
          - field: X-Forwarded-For
            value: $proxy_add_x_forwarded_for
          - field: X-Forwarded-Proto
            value: $scheme
          - field: X-Fowarded-Host
            value: $host
          - field: Host
            value: $http_host
          - field: User-Agent
            value: $http_user_agent
          - field: X-Real-IP
            value: $remote_addr
        buffering: false
      log:
        access:
          - path: /var/log/nginx/access.log
            format: main
            buffer: 1m
            gzip: 5
            flush: 10h
            if: $status
        format:
          - name: main
            format: |
              '$remote_addr - $remote_user [$time_local] "$request" '
              '$status $body_bytes_sent "$http_referer" '
              '"$http_user_agent" "$http_x_forwarded_for"'
        error_log:
          file: /var/log/nginx/error.log
          level: notice
        open_log_file_cache:
          max: 1000
          inactive: 20s
          min_uses: 2
          valid: 1m
      servers: "{{ servers }}"
nginx_confs:
  - /etc/nginx/conf.d/default.conf
