---
# these should be defined in vault.yml
# kc_db_user:
# kc_db_pass:
# kc_root_user:
# kc_root_pass:
# kc_admin_user:
# kc_admin_pass:
# mailcow_client_secret:
# wk_client_secret:
# begin normal vars
domain_name: admin.hierarch.live
kc_db_name: keycloak
kc_db_origin: admin.hierarch.live
kc_realm_name: hierarch
kc_db_host: localhost
kc_admin_url: https://admin.hierarch.live
kc_public_url: https://admin.hierarch.live
kc_hostname_path: "/"
kc_admin_hostname: admin.hierarch.live
kc_debug: true
kc_hostname_port: 7000
kc_http_port: 7000
kc_https_port: 7001
kc_http_host: "0.0.0.0"
kc_https_enabled: false
kc_proxy_mode: edge
kc_realm: hierarch
kc_admin_role: admin
kc_groups:
  developer:
    forgejo_user: "true"
  manager:
    forgejo_user: "true"
  hr:
    forgejo_user: "false"
  it:
    forgejo_user: "true"
  user:
    mailcow_template: default
    synapse_user: "true"
  forgejo_admin:
    forgejo_user: "true"
